### ISSUE TITLE
Dash Enterprise dependency

### ISSUE THREAD

**Issue by michael-c-jablecki** [NOAA-PMEL/dashboard_saildrone#1]
Sadly I don't have a Dash Enterprise subscription. Is there a part of this app which can be used with dash_design_kit? Or could the app fall back to a compatibility mode without the paid module?

**Comment by noaaroland** [comment]
If you are just interested in seeing the data you can use it here: https://viz.pmel.noaa.gov/saildrone.

If you want to use the code to display your own data, you're welcome to it, but without a subscription to Dash Enterprise, you will have to replace all the references to ddk with layout objects from dcc, Dash Mantine and/or Dash Bootstrap.

And you'll need to figure out how to handle the background task management which is done via the redis and celery bundled with Dash Enterprise. And finally you'll need to replace the caching which is done with the Dash Enterprise redis.

**Comment by michael-c-jablecki** [comment]
The main suggestion I'd have would be to offer a minimal dash example demonstrating the core plotting capabilities of placing data onto a map. The overall project is amazing, but such a vignette would enhance the reusability of the lower-level plot components.

**Comment by noaaroland** [comment]
Thank you for your interest. There are tons of places where one can find Dash tutorials and examples. [This is a good one](https://dash.plotly.com/tutorial). The map is built with the [scatter_geo family of Plotly functions](https://plotly.com/python/scatter-plots-on-maps/). You can look at the code to see exactly what calls and parameters were used. The [first three cells of this notebook show how to read data from an ERDDAP](https://github.com/NOAA-PMEL/WRC-TUG/blob/main/examples/app_studio/app_studio_plots.ipynb) with Saildrone data. The [full data API is documented here](https://coastwatch.pfeg.noaa.gov/erddap/tabledap/documentation.html).

This app was purpose-built for our needs. We use github for source code control and are happy if the code is useful to somebody, but tutorials and simplified examples are outside the scope of this project.

**Comment by noaaroland** [comment]
For what it's worth, here is a simple example which I built to demonstrate how to detect which input was selected, but it shows the basics of reading and plotting saildrone data. 

https://github.com/NOAA-PMEL/WRC-TUG/tree/main/examples/callback_context_example

**Comment by michael-c-jablecki** [comment]
Nice stuff :) I will send this on to the team!
